-- HR_DEPARTMENT, HR_EMPLOYEES, HR_GRADE 
-- 사번, 성명, 평가 등급 (GRADE), 성과금 (BONUS) 조회
-- 사번 기준 오름차순

SELECT EMP_NO, EMP_NAME,
CASE 
    WHEN (AVERAGE >= 96) THEN 'S'
    WHEN (AVERAGE BETWEEN 90 AND 96) THEN 'A'
    WHEN (AVERAGE BETWEEN 80 AND 90) THEN 'B'
    ELSE 'C'
END AS GRADE,
CASE
    WHEN (AVERAGE >= 96) THEN SAL * 0.2
    WHEN (AVERAGE BETWEEN 90 AND 96) THEN SAL * 0.15
    WHEN (AVERAGE BETWEEN 80 AND 90) THEN SAL * 0.1
    ELSE 0
END AS BONUS
FROM (
    SELECT e.EMP_NO, e.EMP_NAME, e.SAL, AVG(g.SCORE) AS AVERAGE
    FROM HR_EMPLOYEES e JOIN HR_GRADE g
    ON e.EMP_NO = g.EMP_NO
    GROUP BY e.EMP_NO
) j
ORDER BY EMP_NO;
